### ISSUE TITLE
请教一下如何识别是爬虫请求还是非爬虫请求的

### ISSUE THREAD

**Issue by PolarPeak** [Hentioe/miragend#4]

**Comment by Hentioe** [comment]
本项目的主要目的是混淆网页对抗爬虫，识别爬虫不在范围内。识别爬虫的方法有很多，虽然不能做到很充分的识别，但一般也够用了。例如：

- 最基本的根据 User-Agent
- 利用正常用户不可能访问的蜜罐 URL 收集爬虫
- 统计访问者 IP，把各种非家庭宽带的 IP 整理出来。把来自云服务器或其它奇怪 ISP 对应的 ASN 整个加入名单
- 一些 AI 工具可以主动访问 URL，你可以主动触发他们的爬虫运行拿到他们的 IP 和爬虫特征
- 访问行为分析
- 通过指纹判断爬虫（但个人一般很难，因为能建立的指纹库有限）
